/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccordeonHeadersInterface } from "./components/ip-accordeon/interface/accordeon-headers.interface";
import { AccordeonHeadersInterface as AccordeonHeadersInterface1 } from "./components/ip-accordeon-2/interface/accordeon-headers.interface";
export namespace Components {
    interface IpAccordeon {
        "accordeonHeaders": AccordeonHeadersInterface[] | string;
        "isFirstPanelOpen": boolean;
        "isSingleOpen": boolean;
        "titleTag": string;
    }
    interface IpAccordeon2 {
        "accordeonHeaders": AccordeonHeadersInterface1[] | string;
        "gap": string;
        "isFirstPanelOpen": boolean;
        "isSingleOpen": boolean;
        "titleTag": string;
    }
}
declare global {
    interface HTMLIpAccordeonElement extends Components.IpAccordeon, HTMLStencilElement {
    }
    var HTMLIpAccordeonElement: {
        prototype: HTMLIpAccordeonElement;
        new (): HTMLIpAccordeonElement;
    };
    interface HTMLIpAccordeon2Element extends Components.IpAccordeon2, HTMLStencilElement {
    }
    var HTMLIpAccordeon2Element: {
        prototype: HTMLIpAccordeon2Element;
        new (): HTMLIpAccordeon2Element;
    };
    interface HTMLElementTagNameMap {
        "ip-accordeon": HTMLIpAccordeonElement;
        "ip-accordeon-2": HTMLIpAccordeon2Element;
    }
}
declare namespace LocalJSX {
    interface IpAccordeon {
        "accordeonHeaders"?: AccordeonHeadersInterface[] | string;
        "isFirstPanelOpen"?: boolean;
        "isSingleOpen"?: boolean;
        "titleTag"?: string;
    }
    interface IpAccordeon2 {
        "accordeonHeaders"?: AccordeonHeadersInterface1[] | string;
        "gap"?: string;
        "isFirstPanelOpen"?: boolean;
        "isSingleOpen"?: boolean;
        "titleTag"?: string;
    }
    interface IntrinsicElements {
        "ip-accordeon": IpAccordeon;
        "ip-accordeon-2": IpAccordeon2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-accordeon": LocalJSX.IpAccordeon & JSXBase.HTMLAttributes<HTMLIpAccordeonElement>;
            "ip-accordeon-2": LocalJSX.IpAccordeon2 & JSXBase.HTMLAttributes<HTMLIpAccordeon2Element>;
        }
    }
}
