/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccordeonHeadersInterface } from "./components/ip-accordeon/interface/accordeon-headers.interface";
export namespace Components {
    interface IpAccordeon {
        "accordeonHeaders": AccordeonHeadersInterface[] | string;
        "isFirstPanelOpen": boolean;
        "isSingleOpen": boolean;
        "titleTag": string;
    }
}
declare global {
    interface HTMLIpAccordeonElement extends Components.IpAccordeon, HTMLStencilElement {
    }
    var HTMLIpAccordeonElement: {
        prototype: HTMLIpAccordeonElement;
        new (): HTMLIpAccordeonElement;
    };
    interface HTMLElementTagNameMap {
        "ip-accordeon": HTMLIpAccordeonElement;
    }
}
declare namespace LocalJSX {
    interface IpAccordeon {
        "accordeonHeaders"?: AccordeonHeadersInterface[] | string;
        "isFirstPanelOpen"?: boolean;
        "isSingleOpen"?: boolean;
        "titleTag"?: string;
    }
    interface IntrinsicElements {
        "ip-accordeon": IpAccordeon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-accordeon": LocalJSX.IpAccordeon & JSXBase.HTMLAttributes<HTMLIpAccordeonElement>;
        }
    }
}
